language: node_js
node_js: 12
install:
- npm install
script:
- hexo -v
- hexo g
after_script:
- cd ./public
- git init
- git config user.name "king"
- git config user.email "qiujinwu456@gmail.com"
- git add .
- git commit -m "Update docs"
- git checkout -b gh-pages
- git push --force --quiet "https://$GH_TOKEN@${GH_REF}" gh-pages:gh-pages
branches:
  only:
  - src
env:
  global:
  - GH_REF: github.com/qiujinwu/blog.github.com.git
